### ISSUE TITLE
Assassin Challenge Incorrect

### ISSUE THREAD

**Issue by Edward-Knighton** [Cheneth/coup-online#3]
Currently, if I try to assassinate someone and they challenge my assassin, and then I reveal that I actually have one, they only lose 1 influence. However they should lose two influences, one for the lost challenge, and then 1 for the assassin going through. See link here: https://boardgamegeek.com/thread/1218380/assassin-double-kill
Overall, loving the game though!

**Comment by blendin** [comment]
https://github.com/Cheneth/coup-online/pull/12

**Comment by Cheneth** [comment]
Fix deployed :)
