### ISSUE TITLE
Server code?

### ISSUE THREAD

**Issue by zehauser** [Cheneth/coup-online#4]
This is super awesome! I was curious to read through the codebase because it was such an interesting project to me. Also I was considering making a small change to the event logging (adding a kind of verbose mode). 

I quickly noticed that the server code is not present! It was all removed in early April.

I'm wondering, is the server code going to return to the repo at some point? Why was it removed?

**Comment by Cheneth** [comment]
Hi @zehauser, sorry about that. The code is now back!

**Comment by zehauser** [comment]
You should take back that "sorry", you have no obligations here whatsoever! Instead I'll say thank you for adding it back, and for sharing this with the community.
