### ISSUE TITLE
Copyright

### ISSUE THREAD

**Issue by emersonlaurentino** [Cheneth/coup-online#9]
Hi, I want to make my own version of Coup and before that, I came to look if there was already something open source. I found your repository and I'm curious if you care about copyright, as this is my main fear.

**Comment by alenros** [comment]
Not a lawyer, but It's my understanding that the things that are copyrightable in a game are the visual assets, the name and the specific wording of the rules. game mechanics can not be copyrighted, so if you call your game something else, use your own art, and write your own rules you are probably OK as far as the law cares.

**Comment by emersonlaurentino** [comment]
hm, interesting. I didn't have enough knowledge about this. 

@alenros Can you explain better the difference between game rules and mechanics? for me, it's a very fine line ...

**Comment by alenros** [comment]
Regarding copyright, the rules are the exact words written in the rulebook of the game. you can't copy that verbatim as it's copyrighted. but if you rephrase it you are fine.

**Comment by emersonlaurentino** [comment]
Thanks @alenros!

**Comment by alenros** [comment]
I had a minor heart attack seeing the notification email with your github and the title Copyright - Closed.

**Comment by emersonlaurentino** [comment]
ahahahaaha, sorry!
